from yacs.config import CfgNode as CN

_C = CN()

_C.MODEL = CN()
_C.MODEL.NAME = "SamVINP" # MrcnnVINP

_C.MODEL.SAM = CN()
_C.MODEL.SAM.MDOEL = "vit_h"
_C.MODEL.SAM.CHECKPOINT = ""

_C.MODEL.MRCNN = CN()
_C.MODEL.MRCNN.MODEL = "R50FPN"

_C.MODEL.IADAPTER = CN()
_C.MODEL.IADAPTER.MODEL = "SimFPN"
_C.MODEL.IADAPTER.IN_FEATS = 768
_C.MODEL.IADAPTER.OUT_FEATS = 256
_C.MODEL.IADAPTER.N_LEVELS = 4


_C.MODEL.IHEAD = CN()
_C.MODEL.IHEAD.MODEL = "BN"
_C.MODEL.IHEAD.POOLING = "GeM"

_C.MODEL.INPUT = CN()
_C.MODEL.INPUT.RGB_MEAN = [123.675/255, 116.28/255, 103.53/255]
_C.MODEL.INPUT.RGB_STD = [58.395/255, 57.12/255, 57.375/255]
_C.MODEL.INPUT.INPUT_FORMAT = "RGB"

_C.TRAIN = CN()
_C.TRAIN.DATA = CN()
_C.TRAIN.DATA.NAME = "RoomTour3D"
_C.TRAIN.DATA.SAMPLE_BASE = "video" # or clip
_C.TRAIN.DATA.CLIP_LEN = 4
_C.TRAIN.DATA.RESAMPLE_FPS = 3
_C.TRAIN.DATA.RESIZE = (0.3,2.0) # 1024 * 0.1
_C.TRAIN.DATA.H_FLIP = True
_C.TRAIN.DATA.REA = False
_C.TRAIN.DATA.REA_P = 0.5
_C.TRAIN.DATA.RAND_AFFINE = False
_C.TRAIN.DATA.MIX_UP = False


_C.TRAIN.OPTIM = CN()
_C.TRAIN.OPTIM.OPT = "SGD"
_C.TRAIN.OPTIM.OPT.MOMENTUM = 0.9
_C.TRAIN.OPTIM.WEIGHT_DECAY_IADAPTER = 1e-4
_C.TRAIN.OPTIM.WEIGHT_DECAY_BIAS_IADAPTER = 0.0
_C.TRAIN.OPTIM.WEIGHT_DECAY_IHEAD = _C.TRAIN.OPTIM.WEIGHT_DECAY_IADAPTER
_C.TRAIN.OPTIM.WEIGHT_DECAY_BIAS_IHEAD=_C.TRAIN.OPTIM.WEIGHT_DECAY_BIAS_IADAPTER
_C.TRAIN.OPTIM.INIT_LR_IADAPTER = 0.01
_C.TRAIN.OPTIM.INIT_LR_IHEAD = _C.TRAIN.OPTIM.INIT_LR_IADAPTER
_C.TRAIN.OPTIM.MIN_LR_IADAPTER = 1e-7 # for cosine
_C.TRAIN.OPTIM.MIN_LR_IHEAD = _C.TRAIN.OPTIM.MIN_LR_IADAPTER
_C.TRAIN.OPTIM.WRAMUP_EPOCHS = 0
_C.TRAIN.OPTIM.BATCH_SIZE = 8
_C.TRAIN.OPTIM.N_EPOCHS = 120
_C.TRAIN.OPTIM.SCHED = "step" # cosine, cosine_minf
_C.TRAIN.OPTIM.SCHED_STEPS = [120,]
_C.TRAIN.OPTIM.SCHED_STEP_GAMMA = 0.1

_C.TRAIN.SAVE_PERIOD = 1

_C.TEST = CN()
_C.TEST.ENV = ["ieve",]


_C.OUTPUT_DIR = ""

def get_cfg():
  return _C.clone()